### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by SakshiiRK** [SakshiiRK/Project2#2]
add js and css files

**Comment by TanishLande** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="styles.css"> 
</head>
<body>
  <h1>Hello, World!</h1>
  <p>This is a sample project.</p>
  <script src="main.js" defer></script> 
</body>
</html>
